### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by jsalatas** [samgos/reddbot-telegram#3]
Could you please license it in some free open source license. 

According to github's policy 

> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license

**Comment by deoidh** [comment]
Apologies I'll get this ASAP @jsalatas, sorry for the late reply.
